# Generated by Django 4.2 on 2023-05-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('default', 'Default'), (
                'bonus', 'Bonus')], default='default', max_length=20, verbose_name='Type'),
        ),
    ]
