# Generated by Django 4.2 on 2023-05-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='score',
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name='Score'),
        ),
    ]
