name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Run linting and static analysis
        run: pipenv run flake8

      - name: Set up test database
        run: pipenv run python manage.py migrate --settings=banksystem.test_settings 

      - name: Run unit tests
        run: pipenv run python manage.py test --settings=banksystem.test_settings 

      - name: Set build tag
        run: echo "build-${{ github.run_number }}" >> build-tag.txt

      - name: Create build tag
        run: git tag -a ${{ env.TAG }} -m "Build ${{ env.TAG }}"

      - name: Push build tag
        run: git push origin ${{ env.TAG }}